apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: {name: erpwms}
spec:
  rules:
  - host: erpwms.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: {service: {name: erpwms-api, port: {number: 8080}}}
